#!/usr/bin/env python
__author__ = 'Yunheng(Jackie) Zou'

import numpy as np
import scipy as sp
import copy
from typing import Tuple
from .DataStructures import ScatterCurve
from .TechniqueAnalysis import *



class EChemDataAnalyzer(object):
    """For analyzing data generated by potentialstat """
    def __init__(self, techniqueType: str, data: np.ndarray):
        """

        Args:
            techniqueType: a string state which technique used. Ex: CV, DPV
            data: numpy array that store the data
        """

        # ATTN: How much sense does it make to re-instantiate an analyzer object every time we want to analyze sth?

        self.techniqueType = techniqueType
        self.data = data

    def analyze(self) -> Tuple[np.ndarray, np.ndarray]:

        # TODO: Could you slightly modify the architecture of the analyze method so that it takes the technique as an
        #  argument and returns a dictionary in which each analysis result is tagged with a proper keyword?
        #  e.g. {"Integral Data": integral_data_array, "Peak Data": peak_data_array}

        """
        Analyze the data based on the needs

        Returns: result

        """

        # TODO: Modularize this in a way that we have e.g. a dictionary as a class variable that specifies
        #  - which techniques are implemented for analysis
        #  - the object type of the analyzer
        #  - the name of the returns
        # TODO: Re-write this function to a single operation rather than multiple if statements?
        # TODO: Maybe, one could even make a type of factory pattern out of that?

        if self.techniqueType == "CV":
            cv_data: CVAnalyzer = CVAnalyzer(self.data)
            integral_data_ary, peak_data_ary = cv_data.analysis()
            return integral_data_ary, peak_data_ary

        elif self.techniqueType =="DPV":
            dpv_data: PulseAnalyzer = PulseAnalyzer(self.data)
            peak_data_ary = dpv_data.DPV_analysis()
            return peak_data_ary

        elif self.techniqueType =="SWV":
            swv_data: PulseAnalyzer = PulseAnalyzer(self.data)
            peak_data_ary = swv_data.SWV_analysis()
            return peak_data_ary





