#!/usr/bin/env python
__author__ = 'Yunheng(Jackie) Zou'

import numpy as np
import scipy as sp
import copy
from typing import Tuple
from .DataStructures import ScatterCurve
from .TechniqueAnalysis import *



class EChemDataAnalyzer(object):
    """For analyzing data generated by potentialstat """
    def __init__(self, techniqueType: str,data: np.ndarray):
        """

        Args:
            techniqueType: a string state which technique used. Ex: CV, DPV
            data: numpy array that store the data
        """
        self.techniqueType = techniqueType
        self.data = data

    def analyze(self) -> Tuple[np.ndarray, np.ndarray]:
        """
        Analyze the data based on the needs

        Returns: result

        """
        if self.techniqueType == "CV":
            cv_data: CV_Analyzer = CV_Analyzer(self.data)
            integral_data_ary, peak_data_ary = cv_data.analysis()
            return integral_data_ary, peak_data_ary

        elif self.techniqueType =="DPV":
            dpv_data: Pulse_Analyzer = Pulse_Analyzer(self.data)
            peak_data_ary = dpv_data.DPV_analysis()
            return peak_data_ary
        elif self.techniqueType =="SWV":
            swv_data: Pulse_Analyzer = Pulse_Analyzer(self.data)
            peak_data_ary = swv_data.SWV_analysis()
            return peak_data_ary





